name: CI

on:
  push:
    branches: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}    

    - uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      if: steps.cache-modules.outputs.cache-hit != 'true'
      env:
        PACKAGES_GITHUB_TOKEN: ${{ secrets.PACKAGES_GITHUB_TOKEN }}
      run:  yarn install

    - name: Lint Javascript
      env:
        PACKAGES_GITHUB_TOKEN: ${{ secrets.PACKAGES_GITHUB_TOKEN }}
      run:  yarn lint

  check-types:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}    

    - uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      if: steps.cache-modules.outputs.cache-hit != 'true'
      env:
        PACKAGES_GITHUB_TOKEN: ${{ secrets.PACKAGES_GITHUB_TOKEN }}
      run:  yarn install

    - name: Validate types
      env:
        PACKAGES_GITHUB_TOKEN: ${{ secrets.PACKAGES_GITHUB_TOKEN }}

      run:  yarn types-check

  test:
    needs: [lint, check-types]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}    

    - uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      if: steps.cache-modules.outputs.cache-hit != 'true'
      env:
        PACKAGES_GITHUB_TOKEN: ${{ secrets.PACKAGES_GITHUB_TOKEN }}
      run:  yarn install

    - name: Test javascript
      env:
        PACKAGES_GITHUB_TOKEN: ${{ secrets.PACKAGES_GITHUB_TOKEN }}
      run:  yarn test:coverage
